### ISSUE TITLE
Add a new dataset & benchmark paper

### ISSUE THREAD

**Issue by Zhuofeng-Li** [yhLeeee/Awesome-LLMs-in-Graph-tasks#10]
Thanks for this comprehensive collection of works!

I want to share our recent TEG (textual-edge graph featuring rich
 textual descriptions on nodes and edges) Datasets and Benchmark work published in NeurIPS 2024.

_(2024.05)_ [NeurIPS 2024] **TEG-DB: A Comprehensive Dataset and Benchmark of Textual-Edge Graphs** [[pdf](https://arxiv.org/abs/2406.10310)][[code](https://github.com/Zhuofeng-Li/TEG-Benchmark/tree/main)][[datasets](https://huggingface.co/datasets/ZhuofengLi/TEG-Datasets/tree/main)]

**Comment by NineAbyss** [comment]
Thank you for your contribution! Now we have added this paper.
