### ISSUE TITLE
The code link of InstructGLM(2023.08) is wrong. 

### ISSUE THREAD

**Issue by RuosongYe** [yhLeeee/Awesome-LLMs-in-Graph-tasks#2]
The code link of InstructGLM(2023.08) is wrong. 
Our official code link is https://github.com/agiresearch/InstructGLM

May you kindly help fix this? (Also in the table 1 of your paper.)

Thank you so much.

**Comment by yhLeeee** [comment]
Thank you for your kind reminder, and I apologize for the mistake. 

I will make the changes in the repo ASAP, and the modifications in the paper will be reflected in the next version (coming soon).

Thanks.
