### ISSUE TITLE
Some suggestions for the writing template 

### ISSUE THREAD

**Issue by ZhongLIFR** [yhLeeee/Awesome-LLMs-in-Graph-tasks#5]
Hi authors,

Thank you for this great survey. After reading your work, I have some suggestions concerning the writing of this survey (especially  the formatting):
1. the current ArXiv version does not have page numbers;
2. the reference style (using names and year) maybe take too many places; more importantly, if I print it out but don't read it on computers, it is so hard to find the corresponding references. (According to my experiences, most survey papers utilise numbers as the reference style)

I hope these comments can help further improve this great survey.

Best,

Zhong

**Comment by NineAbyss** [comment]
Hello!
Thanks for your interests and your suggestions! 
We will consider add the page numbers and revise the references style in the next version. I believe it will help develop this survey.
Thank you again.

**Comment by NineAbyss** [comment]
> Hi authors,
> 
> Thank you for this great survey. After reading your work, I have some suggestions concerning the writing of this survey (especially the formatting):
> 
> 1. the current ArXiv version does not have page numbers;
> 2. the reference style (using names and year) maybe take too many places; more importantly, if I print it out but don't read it on computers, it is so hard to find the corresponding references. (According to my experiences, most survey papers utilise numbers as the reference style)
> 
> I hope these comments can help further improve this great survey.
> 
> Best,
> 
> Zhong

Hello! 
Thanks for your interest and suggestions! We will consider adding the page numbers and revising the reference style in the next version. I believe it will help develop this survey. 
We appreciate your comments again.
